/// Renders the plan back to `PROJECT_PLAN.md` — a generated, read-only view
/// that keeps the shape the hand-written file had, so anything that still
/// reads the markdown (a person, an old command) sees what it expects.
library;

import 'graph.dart';
import 'import_md.dart' show humanBoxesMarker;
import 'model.dart';

String renderPlanMarkdown(Plan plan) {
  final g = Graph(plan);
  final b = StringBuffer();
  b.writeln('# ${plan.manifest.projectName} — project plan');
  b.writeln();
  b.writeln('<!-- GENERATED by `kit render plan` from plan/ — do not edit this file. -->');
  b.writeln('<!-- Edit plan/steps/<id>.yaml and plan/items/<id>.yaml, then re-render. -->');
  b.writeln();
  b.writeln('Status lives in `plan/`. This file is a rendering of it: `- [x]` is a step');
  b.writeln('whose `status` is `done`; a step whose code is finished but whose human boxes');
  b.writeln('are open shows `- [ ]` with a `state:` line saying so. Human boxes are items');
  b.writeln('(`plan/items/`) that name the step in `blocks:`; `kit blocks <id>` lists them.');
  b.writeln();
  b.writeln('Work order is `rank`, top to bottom. `kit next` says what is next.');
  b.writeln();
  b.writeln('---');
  b.writeln();

  for (final s in plan.steps) {
    final v = g.view(s);
    final num = s.number ?? '';
    b.writeln('## Step $num — ${s.title}');
    b.writeln(s.status == StepStatus.done ? '- [x]' : '- [ ]');
    if (v.state != StepState.done && v.state != StepState.ready && v.state != StepState.blocked) {
      b.writeln('- state: ${_stateLine(v)}');
    } else if (v.state == StepState.blocked) {
      b.writeln('- state: blocked — waiting on ${v.missingDeps.map((d) => d.id).join(', ')}');
    }
    b.writeln('- id: ${s.id}');
    b.writeln('- depends_on: ${s.dependsOn.isEmpty ? 'none' : s.dependsOn.join(', ')}');
    for (final e in s.meta.entries) {
      b.writeln('- ${e.key}: ${e.value}');
    }
    final boxes = _humanBoxes(plan, s);
    var placed = false;
    for (final sec in s.sections) {
      b.writeln();
      b.writeln('### ${sec.title}');
      var body = sec.body;
      if (body.contains(humanBoxesMarker)) {
        body = body.replaceAll(humanBoxesMarker, boxes.isEmpty ? '' : boxes);
        placed = true;
      }
      b.write(body.endsWith('\n') || body.isEmpty ? body : '$body\n');
    }
    if (!placed && boxes.isNotEmpty) {
      b.writeln();
      b.writeln('### Your part (human)');
      b.writeln();
      b.writeln('The step\'s checkbox stays `[ ]` until these are checked:');
      b.writeln();
      b.write(boxes);
    }
    b.writeln();
    b.writeln('---');
    b.writeln();
  }
  return b.toString();
}

String _stateLine(StepView v) {
  switch (v.state) {
    case StepState.active:
      return 'active — gates pending: ${v.pendingGates.map((g) => g.name).join(', ')}';
    case StepState.codeComplete:
      return 'code complete — waiting on ${v.openBlockers.length} human item(s)';
    case StepState.flippable:
      return 'every gate passed and nothing blocks it — flip me';
    case StepState.waiting:
      return 'waiting';
    case StepState.done:
    case StepState.ready:
    case StepState.blocked:
      return v.state.name;
  }
}

/// The checkbox list for a step's human items, done ones included so the
/// history reads the same as it did in the hand-written plan.
String _humanBoxes(Plan plan, Step s) {
  final all = [for (final i in plan.items) if (i.blocks.contains(s.id)) i];
  if (all.isEmpty) return '';
  final b = StringBuffer();
  for (final i in all) {
    final mark = i.status == ItemStatus.open ? ' ' : 'x';
    final text = i.status == ItemStatus.dropped ? '~~${i.title}~~' : i.title;
    b.writeln('  - [$mark] $text *(item `${i.id}`)*');
  }
  return b.toString();
}
