// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxMUA6ZKpEL25ZhFmhOM8oWSofWDWXrkI',
    appId: '1:187450447184:android:f955ed6ac73c9ed2cf0855',
    messagingSenderId: '187450447184',
    projectId: 'okeyacarmi-dcb8c',
    storageBucket: 'okeyacarmi-dcb8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu-wTLAzOvU3b7buXEOyWW-NKMDRoO7uw',
    appId: '1:187450447184:ios:a44ee4460171b5f4cf0855',
    messagingSenderId: '187450447184',
    projectId: 'okeyacarmi-dcb8c',
    storageBucket: 'okeyacarmi-dcb8c.firebasestorage.app',
    androidClientId:
        '187450447184-1pqoj5ldjkogdvroie22q5k32bo1elus.apps.googleusercontent.com',
    iosClientId:
        '187450447184-t96rvic1nbodir8ce7u7vmbp77mn0clu.apps.googleusercontent.com',
    iosBundleId: 'com.okeyacarmi.okeyAcarMi',
  );
}
